### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by richpeck** [ricardoemerson/font-ionicons-rails#1]
Working with Heroku? It's currently not precompiling the font for me :(

**Comment by richpeck** [comment]
Solution is to add the ionicons font files to precompile path:

```
#config/initializers/assets.rb
Rails.application.config.assets.precompile += %w( ionicons.eot ionicons.ttf ionicons.svg ionicons.woff)

```

For the engine, you should add the [following](https://github.com/richpeck/exception_handler/blob/master/lib/exception_handler.rb#L50) to your Engine class:

```
class Engine < ::Rails::Engine
  config.assets.precompile << %w( ionicons.eot ionicons.ttf ionicons.svg ionicons.woff )
end
```

This will remove the need to include the files manually.
--

I can submit PR if required.

**Comment by ricardoemerson** [comment]
Hello @richpeck, thank you for your suggestion and inform you that I have done the correction suggested by you.

Please check if worked as expected.

**Comment by richpeck** [comment]
Checking, there is a another problem now with Rails 5.0.0 -- you've got Railties < 5.0 as a dependency whilst Rails 5.0.0 ships with Rails 5.0.0. This means that the < 5.0.0 reference is invalid and causes conflict error.

You need to [change the dependency](https://github.com/ricardoemerson/font-ionicons-rails/blob/master/font-ionicons-rails.gemspec#L18) to < 6.0:

    gem.add_dependency "railties", ">= 3.2", "< 6.0"

**Comment by ricardoemerson** [comment]
Hello @richpeck, thanks again for your suggestions. Changes made.

**Comment by richpeck** [comment]
Works very very well now - thank you!
